### ISSUE TITLE
Run some CI tests every few hours to check authentication flow

### ISSUE THREAD

**Issue by michaelarnauts** [add-ons/plugin.video.vtm.go#217]
Given the recent breakages in the login flow, it would make sense to run some CI tests related to authentication every few hours. Maybe like every 6 hours, that's 4 times a day.

@dagwieers can you help with that? I think you've set that up for VRT NU. Do we get an e-mail when something breaks?

**Comment by dagwieers** [comment]
Yes, if a workflow fails to work you get an email. You can see how we do this for VRT NU here: https://github.com/add-ons/plugin.video.vrt.nu/blob/master/.github/workflows/status.yml

We selected a set of unit tests that perform a specific test we want to make sure works. We don't run all unit tests because those often test the same code paths multiple times needlessly and this is run every 30 minutes.
